allowBuilds:
  '@firebase/util': true
  core-js: true
  protobufjs: true
  sharp: false
  unrs-resolver: false
nodeLinker: hoisted
patchedDependencies:
  '@mediapipe/face_detection': patches/@mediapipe__face_detection.patch
  '@mediapipe/face_mesh': patches/@mediapipe__face_mesh.patch
